package com.wyl.tms.model;

import java.util.ArrayList;
import java.util.List;

public class ChildGoodsOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public ChildGoodsOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChildGoodsOrderIdIsNull() {
            addCriterion("childGoodsOrderId is null");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdIsNotNull() {
            addCriterion("childGoodsOrderId is not null");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdEqualTo(Integer value) {
            addCriterion("childGoodsOrderId =", value, "childGoodsOrderId");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdNotEqualTo(Integer value) {
            addCriterion("childGoodsOrderId <>", value, "childGoodsOrderId");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdGreaterThan(Integer value) {
            addCriterion("childGoodsOrderId >", value, "childGoodsOrderId");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("childGoodsOrderId >=", value, "childGoodsOrderId");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdLessThan(Integer value) {
            addCriterion("childGoodsOrderId <", value, "childGoodsOrderId");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("childGoodsOrderId <=", value, "childGoodsOrderId");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdIn(List<Integer> values) {
            addCriterion("childGoodsOrderId in", values, "childGoodsOrderId");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdNotIn(List<Integer> values) {
            addCriterion("childGoodsOrderId not in", values, "childGoodsOrderId");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("childGoodsOrderId between", value1, value2, "childGoodsOrderId");
            return (Criteria) this;
        }

        public Criteria andChildGoodsOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("childGoodsOrderId not between", value1, value2, "childGoodsOrderId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goodsId is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goodsId is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Integer value) {
            addCriterion("goodsId =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Integer value) {
            addCriterion("goodsId <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Integer value) {
            addCriterion("goodsId >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodsId >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Integer value) {
            addCriterion("goodsId <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("goodsId <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Integer> values) {
            addCriterion("goodsId in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Integer> values) {
            addCriterion("goodsId not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("goodsId between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("goodsId not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Integer value) {
            addCriterion("quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Integer value) {
            addCriterion("quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Integer value) {
            addCriterion("quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Integer value) {
            addCriterion("quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Integer> values) {
            addCriterion("quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Integer> values) {
            addCriterion("quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Integer value1, Integer value2) {
            addCriterion("quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andPriceSumIsNull() {
            addCriterion("priceSum is null");
            return (Criteria) this;
        }

        public Criteria andPriceSumIsNotNull() {
            addCriterion("priceSum is not null");
            return (Criteria) this;
        }

        public Criteria andPriceSumEqualTo(Double value) {
            addCriterion("priceSum =", value, "priceSum");
            return (Criteria) this;
        }

        public Criteria andPriceSumNotEqualTo(Double value) {
            addCriterion("priceSum <>", value, "priceSum");
            return (Criteria) this;
        }

        public Criteria andPriceSumGreaterThan(Double value) {
            addCriterion("priceSum >", value, "priceSum");
            return (Criteria) this;
        }

        public Criteria andPriceSumGreaterThanOrEqualTo(Double value) {
            addCriterion("priceSum >=", value, "priceSum");
            return (Criteria) this;
        }

        public Criteria andPriceSumLessThan(Double value) {
            addCriterion("priceSum <", value, "priceSum");
            return (Criteria) this;
        }

        public Criteria andPriceSumLessThanOrEqualTo(Double value) {
            addCriterion("priceSum <=", value, "priceSum");
            return (Criteria) this;
        }

        public Criteria andPriceSumIn(List<Double> values) {
            addCriterion("priceSum in", values, "priceSum");
            return (Criteria) this;
        }

        public Criteria andPriceSumNotIn(List<Double> values) {
            addCriterion("priceSum not in", values, "priceSum");
            return (Criteria) this;
        }

        public Criteria andPriceSumBetween(Double value1, Double value2) {
            addCriterion("priceSum between", value1, value2, "priceSum");
            return (Criteria) this;
        }

        public Criteria andPriceSumNotBetween(Double value1, Double value2) {
            addCriterion("priceSum not between", value1, value2, "priceSum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table child_goods_order
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 10 11:04:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}