package com.wyl.tms.model;

import java.util.ArrayList;
import java.util.List;

public class TheaterInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public TheaterInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTheaterIdIsNull() {
            addCriterion("theaterId is null");
            return (Criteria) this;
        }

        public Criteria andTheaterIdIsNotNull() {
            addCriterion("theaterId is not null");
            return (Criteria) this;
        }

        public Criteria andTheaterIdEqualTo(Integer value) {
            addCriterion("theaterId =", value, "theaterId");
            return (Criteria) this;
        }

        public Criteria andTheaterIdNotEqualTo(Integer value) {
            addCriterion("theaterId <>", value, "theaterId");
            return (Criteria) this;
        }

        public Criteria andTheaterIdGreaterThan(Integer value) {
            addCriterion("theaterId >", value, "theaterId");
            return (Criteria) this;
        }

        public Criteria andTheaterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("theaterId >=", value, "theaterId");
            return (Criteria) this;
        }

        public Criteria andTheaterIdLessThan(Integer value) {
            addCriterion("theaterId <", value, "theaterId");
            return (Criteria) this;
        }

        public Criteria andTheaterIdLessThanOrEqualTo(Integer value) {
            addCriterion("theaterId <=", value, "theaterId");
            return (Criteria) this;
        }

        public Criteria andTheaterIdIn(List<Integer> values) {
            addCriterion("theaterId in", values, "theaterId");
            return (Criteria) this;
        }

        public Criteria andTheaterIdNotIn(List<Integer> values) {
            addCriterion("theaterId not in", values, "theaterId");
            return (Criteria) this;
        }

        public Criteria andTheaterIdBetween(Integer value1, Integer value2) {
            addCriterion("theaterId between", value1, value2, "theaterId");
            return (Criteria) this;
        }

        public Criteria andTheaterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("theaterId not between", value1, value2, "theaterId");
            return (Criteria) this;
        }

        public Criteria andTheaterNameIsNull() {
            addCriterion("theaterName is null");
            return (Criteria) this;
        }

        public Criteria andTheaterNameIsNotNull() {
            addCriterion("theaterName is not null");
            return (Criteria) this;
        }

        public Criteria andTheaterNameEqualTo(String value) {
            addCriterion("theaterName =", value, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameNotEqualTo(String value) {
            addCriterion("theaterName <>", value, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameGreaterThan(String value) {
            addCriterion("theaterName >", value, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameGreaterThanOrEqualTo(String value) {
            addCriterion("theaterName >=", value, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameLessThan(String value) {
            addCriterion("theaterName <", value, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameLessThanOrEqualTo(String value) {
            addCriterion("theaterName <=", value, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameLike(String value) {
            addCriterion("theaterName like", value, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameNotLike(String value) {
            addCriterion("theaterName not like", value, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameIn(List<String> values) {
            addCriterion("theaterName in", values, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameNotIn(List<String> values) {
            addCriterion("theaterName not in", values, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameBetween(String value1, String value2) {
            addCriterion("theaterName between", value1, value2, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterNameNotBetween(String value1, String value2) {
            addCriterion("theaterName not between", value1, value2, "theaterName");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressIsNull() {
            addCriterion("theaterAddress is null");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressIsNotNull() {
            addCriterion("theaterAddress is not null");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressEqualTo(String value) {
            addCriterion("theaterAddress =", value, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressNotEqualTo(String value) {
            addCriterion("theaterAddress <>", value, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressGreaterThan(String value) {
            addCriterion("theaterAddress >", value, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressGreaterThanOrEqualTo(String value) {
            addCriterion("theaterAddress >=", value, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressLessThan(String value) {
            addCriterion("theaterAddress <", value, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressLessThanOrEqualTo(String value) {
            addCriterion("theaterAddress <=", value, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressLike(String value) {
            addCriterion("theaterAddress like", value, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressNotLike(String value) {
            addCriterion("theaterAddress not like", value, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressIn(List<String> values) {
            addCriterion("theaterAddress in", values, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressNotIn(List<String> values) {
            addCriterion("theaterAddress not in", values, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressBetween(String value1, String value2) {
            addCriterion("theaterAddress between", value1, value2, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andTheaterAddressNotBetween(String value1, String value2) {
            addCriterion("theaterAddress not between", value1, value2, "theaterAddress");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("phoneNumber is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("phoneNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("phoneNumber =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("phoneNumber <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("phoneNumber >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("phoneNumber >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("phoneNumber <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("phoneNumber <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("phoneNumber like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("phoneNumber not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("phoneNumber in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("phoneNumber not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("phoneNumber between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("phoneNumber not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionIsNull() {
            addCriterion("theaterDescription is null");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionIsNotNull() {
            addCriterion("theaterDescription is not null");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionEqualTo(String value) {
            addCriterion("theaterDescription =", value, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionNotEqualTo(String value) {
            addCriterion("theaterDescription <>", value, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionGreaterThan(String value) {
            addCriterion("theaterDescription >", value, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("theaterDescription >=", value, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionLessThan(String value) {
            addCriterion("theaterDescription <", value, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionLessThanOrEqualTo(String value) {
            addCriterion("theaterDescription <=", value, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionLike(String value) {
            addCriterion("theaterDescription like", value, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionNotLike(String value) {
            addCriterion("theaterDescription not like", value, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionIn(List<String> values) {
            addCriterion("theaterDescription in", values, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionNotIn(List<String> values) {
            addCriterion("theaterDescription not in", values, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionBetween(String value1, String value2) {
            addCriterion("theaterDescription between", value1, value2, "theaterDescription");
            return (Criteria) this;
        }

        public Criteria andTheaterDescriptionNotBetween(String value1, String value2) {
            addCriterion("theaterDescription not between", value1, value2, "theaterDescription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theater_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 10 11:04:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theater_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}