package com.wyl.tms.dao;

import com.wyl.tms.model.ChildGoodsOrder;
import com.wyl.tms.model.ChildGoodsOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChildGoodsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    long countByExample(ChildGoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByExample(ChildGoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer childGoodsOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insert(ChildGoodsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insertSelective(ChildGoodsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    List<ChildGoodsOrder> selectByExample(ChildGoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    ChildGoodsOrder selectByPrimaryKey(Integer childGoodsOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChildGoodsOrder record, @Param("example") ChildGoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExample(@Param("record") ChildGoodsOrder record, @Param("example") ChildGoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(ChildGoodsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_goods_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKey(ChildGoodsOrder record);
}