package com.wyl.tms.dao;

import com.wyl.tms.model.CouponInfo;
import com.wyl.tms.model.CouponInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    long countByExample(CouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByExample(CouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insert(CouponInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insertSelective(CouponInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    List<CouponInfo> selectByExample(CouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    CouponInfo selectByPrimaryKey(Integer couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") CouponInfo record, @Param("example") CouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExample(@Param("record") CouponInfo record, @Param("example") CouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(CouponInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKey(CouponInfo record);
}