package com.wyl.tms.dao;

import com.wyl.tms.model.FilmHallInfo;
import com.wyl.tms.model.FilmHallInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmHallInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    long countByExample(FilmHallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByExample(FilmHallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer filmHallNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insert(FilmHallInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insertSelective(FilmHallInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    List<FilmHallInfo> selectByExample(FilmHallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    FilmHallInfo selectByPrimaryKey(Integer filmHallNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") FilmHallInfo record, @Param("example") FilmHallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExample(@Param("record") FilmHallInfo record, @Param("example") FilmHallInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(FilmHallInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_hall_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKey(FilmHallInfo record);
}