package com.wyl.tms.dao;

import com.wyl.tms.model.FilmArrangement;
import com.wyl.tms.model.FilmArrangementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmArrangementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    long countByExample(FilmArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByExample(FilmArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer arrangementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insert(FilmArrangement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insertSelective(FilmArrangement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    List<FilmArrangement> selectByExample(FilmArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    FilmArrangement selectByPrimaryKey(Integer arrangementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") FilmArrangement record, @Param("example") FilmArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExample(@Param("record") FilmArrangement record, @Param("example") FilmArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(FilmArrangement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_arrangement
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKey(FilmArrangement record);
}