package com.wyl.tms.dao;

import com.wyl.tms.model.FilmInfo;
import com.wyl.tms.model.FilmInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    long countByExample(FilmInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByExample(FilmInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer filmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insert(FilmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insertSelective(FilmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    List<FilmInfo> selectByExample(FilmInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    FilmInfo selectByPrimaryKey(Integer filmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") FilmInfo record, @Param("example") FilmInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExample(@Param("record") FilmInfo record, @Param("example") FilmInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(FilmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKey(FilmInfo record);
}