package com.wyl.tms.dao;

import com.wyl.tms.model.MemberType;
import com.wyl.tms.model.MemberTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    long countByExample(MemberTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByExample(MemberTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByPrimaryKey(Boolean memberTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insert(MemberType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insertSelective(MemberType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    List<MemberType> selectByExample(MemberTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    MemberType selectByPrimaryKey(Boolean memberTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") MemberType record, @Param("example") MemberTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExample(@Param("record") MemberType record, @Param("example") MemberTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(MemberType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_type
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKey(MemberType record);
}