package com.wyl.tms.dao;

import com.wyl.tms.model.SeatSelectionSituation;
import com.wyl.tms.model.SeatSelectionSituationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeatSelectionSituationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    long countByExample(SeatSelectionSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByExample(SeatSelectionSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer seatSelectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insert(SeatSelectionSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insertSelective(SeatSelectionSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    List<SeatSelectionSituation> selectByExample(SeatSelectionSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    SeatSelectionSituation selectByPrimaryKey(Integer seatSelectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") SeatSelectionSituation record, @Param("example") SeatSelectionSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExample(@Param("record") SeatSelectionSituation record, @Param("example") SeatSelectionSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(SeatSelectionSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat_selection_situation
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKey(SeatSelectionSituation record);
}