package com.wyl.tms.dao;

import com.wyl.tms.model.UserFilmOrder;
import com.wyl.tms.model.UserFilmOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFilmOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    long countByExample(UserFilmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByExample(UserFilmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer filmOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insert(UserFilmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insertSelective(UserFilmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    List<UserFilmOrder> selectByExample(UserFilmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    UserFilmOrder selectByPrimaryKey(Integer filmOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserFilmOrder record, @Param("example") UserFilmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExample(@Param("record") UserFilmOrder record, @Param("example") UserFilmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(UserFilmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_order
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKey(UserFilmOrder record);
}