package com.wyl.tms.dao;

import com.wyl.tms.model.UserFilmInfo;
import com.wyl.tms.model.UserFilmInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFilmInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    long countByExample(UserFilmInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByExample(UserFilmInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int deleteByPrimaryKey(Integer userFilmInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insert(UserFilmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int insertSelective(UserFilmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    List<UserFilmInfo> selectByExample(UserFilmInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    UserFilmInfo selectByPrimaryKey(Integer userFilmInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserFilmInfo record, @Param("example") UserFilmInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByExample(@Param("record") UserFilmInfo record, @Param("example") UserFilmInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKeySelective(UserFilmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_film_info
     *
     * @mbg.generated Wed Apr 10 11:04:15 CST 2019
     */
    int updateByPrimaryKey(UserFilmInfo record);
}